import type { Review } from "./reviews";

/** Avis Google vérifiés manuellement — fiche Maps sans adresse fixe (zone de service). */
export const MANUAL_REVIEWS: Review[] = [
  {
    id: "oceane-muel",
    name: "Océane Muel",
    rating: 5,
    text: "Très bon service rendu par Cassard sanitaire pour une fuite dans mon appartement : le problème a été vite cerné et très bien résolu. Je recommande ses services. Merci beaucoup.",
    date: "mai 2026",
    relativeTime: "il y a une semaine",
    profilePhotoUrl: null,
  },
  {
    id: "mameri-sofiane",
    name: "MAMERI Sofiane",
    rating: 5,
    text: "Un grand merci pour l'intervention rapide, toilette cassée en plein jour férié. Professionnel, efficace et sympathique.",
    date: "mai 2026",
    relativeTime: "il y a 2 semaines",
    profilePhotoUrl: null,
  },
  {
    id: "rudy-monier",
    name: "Rudy Monier",
    rating: 5,
    text: "Venu hier soir assez tard pour régler une fuite sur un radiateur. Parfait. Je recommande.",
    date: "avril 2026",
    relativeTime: "il y a 4 semaines",
    profilePhotoUrl: null,
  },
  {
    id: "valerie-de-lattes",
    name: "Valérie de Lattes",
    rating: 5,
    text: "Fuite à mon compteur, mon assureur m'envoie M. Cassard. Il est réactif, aimable, pro, rapide. Panne réparée. Je le recommande.",
    date: "mars 2026",
    relativeTime: "il y a un mois",
    profilePhotoUrl: null,
  },
  {
    id: "chris-ondara",
    name: "Chris Ondara",
    rating: 5,
    text: "M. Cassard est intervenu pour nos canalisations de chauffage. À l'écoute, très disponible et poli. Bonne continuation !",
    date: "février 2026",
    relativeTime: "il y a 2 mois",
    profilePhotoUrl: null,
  },
  {
    id: "yacin-ait-allal",
    name: "Yacin Ait Allal",
    rating: 5,
    text: "Merci encore pour votre réactivité et professionnalisme. Je recommande à 100 %.",
    date: "mars 2026",
    relativeTime: "il y a 2 mois",
    profilePhotoUrl: null,
  },
  {
    id: "d-laurent",
    name: "D. Laurent",
    rating: 5,
    text: "Plombier très consciencieux et professionnel. Il est intervenu un dimanche matin avec le sourire — et oui, il bosse le week-end !",
    date: "janvier 2026",
    relativeTime: "il y a 3 mois",
    profilePhotoUrl: null,
  },
  {
    id: "jeremy-bec",
    name: "Jérémy Bec",
    rating: 5,
    text: "Super intervention, rapide, efficace, très professionnel. Je recommande.",
    date: "janvier 2026",
    relativeTime: "il y a 3 mois",
    profilePhotoUrl: null,
  },
  {
    id: "yann",
    name: "Yann",
    rating: 5,
    text: "Mon chauffe-eau a rendu l'âme et fuyait énormément. M. Cassard est intervenu très rapidement pour le mettre en sécurité. Très professionnel, sérieux et sympathique.",
    date: "février 2026",
    relativeTime: "il y a 3 mois",
    profilePhotoUrl: null,
  },
  {
    id: "hugo-hugo",
    name: "Hugo",
    rating: 5,
    text: "Très satisfait de l'intervention rapide. Panne trouvée tout de suite et réparée dans l'heure impartie avec l'assurance. À recommander.",
    date: "février 2026",
    relativeTime: "il y a 3 mois",
    profilePhotoUrl: null,
  },
  {
    id: "ss-ss",
    name: "Ss Ss",
    rating: 5,
    text: "Intervention chez moi dans le cadre d'un dégât des eaux. Très rapide, très professionnel, travail minutieux et chantier laissé propre. Ponctuel et pédagogue.",
    date: "janvier 2026",
    relativeTime: "il y a 4 mois",
    profilePhotoUrl: null,
  },
  {
    id: "audrey-tribout",
    name: "Audrey Tribout",
    rating: 5,
    text: "Très satisfaite : intervention rapide, à l'heure, origine de la panne trouvée immédiatement. Travail propre, explications claires, tarifs transparents. Je recommande vivement.",
    date: "novembre 2025",
    relativeTime: "il y a 5 mois",
    profilePhotoUrl: null,
  },
  {
    id: "quentin-inderbitzin",
    name: "Quentin Inderbitzin",
    rating: 5,
    text: "Super plombier ! Efficace, super pro et sympa. Il a su intervenir sur une urgence. Je le recommande à fond.",
    date: "décembre 2025",
    relativeTime: "il y a 5 mois",
    profilePhotoUrl: null,
  },
  {
    id: "marie-gabriel",
    name: "Marie Gabriel",
    rating: 5,
    text: "Super travail ! Jean est très professionnel et très sympathique, il nous a sauvés en dernière minute. Je recommande vivement.",
    date: "décembre 2025",
    relativeTime: "il y a 5 mois",
    profilePhotoUrl: null,
  },
  {
    id: "arnaud-odoul",
    name: "Arnaud Odoul",
    rating: 5,
    text: "Très satisfait : intervention un dimanche matin dans l'urgence, parfaitement réalisée. Plombier très professionnel et extrêmement sympathique.",
    date: "novembre 2025",
    relativeTime: "il y a 5 mois",
    profilePhotoUrl: null,
  },
  {
    id: "evelyne-leost",
    name: "Evelyne Leost",
    rating: 5,
    text: "Professionnel sérieux, ponctuel, réactif et très compétent. Rencontré à l'occasion d'un dépannage envoyé par mon assurance. Je recommande sans réserve.",
    date: "novembre 2025",
    relativeTime: "il y a 6 mois",
    profilePhotoUrl: null,
  },
  {
    id: "veronique-cherel",
    name: "Véronique Cherel",
    rating: 5,
    text: "Entièrement satisfaite : rapidité d'intervention sur une grosse fuite, professionnalisme, amabilité, sérieux et suivi des papiers.",
    date: "novembre 2025",
    relativeTime: "il y a 6 mois",
    profilePhotoUrl: null,
  },
  {
    id: "sebastien-garcia",
    name: "Sebastien Garcia",
    rating: 5,
    text: "Super professionnel, envoyé par mon assurance pour un changement de chauffe-eau en urgence. Sérieux, ponctuel, réactif et consciencieux.",
    date: "novembre 2025",
    relativeTime: "il y a 6 mois",
    profilePhotoUrl: null,
  },
  {
    id: "roger-perrin",
    name: "Roger Perrin",
    rating: 5,
    text: "Excellent : rapidité, ponctualité, professionnalisme, sérieux et en plus sympathique. Recommandé sans aucune réserve.",
    date: "octobre 2025",
    relativeTime: "il y a 6 mois",
    profilePhotoUrl: null,
  },
  {
    id: "raulo-nadege",
    name: "Raulo Nadege",
    rating: 5,
    text: "Intervention rapide effectuée avec professionnalisme, sérieux et amabilité. Merci.",
    date: "octobre 2025",
    relativeTime: "il y a 7 mois",
    profilePhotoUrl: null,
  },
];
